//! The studio's `tokens.css` is what the core's theme table declares (ADR-0252).
//!
//! `studio/renderer/tokens.css` is generated by [`theme::css`] from
//! [`theme::THEME`], the table every engine-drawn surface reads. A hand edit in
//! the file, or a theme change without a regeneration, fails here.
//! `RLX_UPDATE_UI_TOKENS=1` rewrites it — the same shape
//! `the_player_schema_snapshot_is_current` uses (ADR-0170, ADR-0190).
//!
//! GPU-free: a string comparison.

use std::path::{Path, PathBuf};

use rlx_core::render::theme;

/// Where the generated stylesheet is committed, relative to the repo root.
const TOKENS_CSS: &str = "studio/renderer/tokens.css";

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("core has a workspace-root parent")
        .to_path_buf()
}

/// **The committed `tokens.css` is what the theme table renders**, byte for byte
/// bar the line endings.
///
/// Regenerate with
/// `RLX_UPDATE_UI_TOKENS=1 cargo nextest run -p rlx-core --test suite ui_tokens::`.
#[test]
fn the_studio_tokens_are_what_the_theme_declares() {
    let path = repo_root().join(TOKENS_CSS);
    let generated = theme::css();
    if std::env::var_os("RLX_UPDATE_UI_TOKENS").is_some() {
        std::fs::write(&path, &generated)
            .unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
    }
    let committed = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{TOKENS_CSS} cannot be read: {e}"));
    // Compared without the line endings, so a clone that checked the file out
    // as CRLF does not fail a test about its content.
    assert!(
        committed.replace("\r\n", "\n") == generated,
        "{TOKENS_CSS} is not what core/src/render/theme.rs declares. Regenerate it with\n\
         \n    RLX_UPDATE_UI_TOKENS=1 cargo nextest run -p rlx-core --test suite ui_tokens::\n\n\
         It is rendered by rlx_core::render::theme::css(); a hand edit is what this \
         fails on. The generated text is:\n\n{generated}"
    );
}

/// **Every colour role reaches the stylesheet.** A role added to the table and
/// forgotten in the renderer would leave the studio one role short of the
/// engine, silently.
#[test]
fn every_colour_role_is_a_custom_property() {
    let css = theme::css();
    for name in [
        "bg",
        "panel",
        "panel-edge",
        "scanline",
        "text",
        "text-dim",
        "text-faint",
        "accent",
        "highlight",
        "favourite",
        "good",
        "info",
        "warn",
        "error",
        "trough",
    ] {
        assert!(
            css.contains(&format!("  --{name}: #")),
            "--{name} is missing from the generated tokens:\n{css}"
        );
    }
    assert!(
        css.contains(&format!("  --accent: {};", theme::THEME.accent.css())),
        "the accent must be spelled from the table"
    );
}
