//! Build script: generate the embedded preset list from `presets/*.toml` so
//! shipping a preset is dropping a file, not editing Rust (ADR-0022, Plan 0021).
//!
//! `include_str!` cannot expand a directory — it takes only a string literal —
//! so the list was hand-maintained. We instead glob `presets/` here at build
//! time and emit a generated `EMBEDDED` slice whose entries are still
//! `include_str!(<absolute path>)` tuples, so rustc embeds the bytes exactly as
//! a hand-written array would. Zero dependency: a `read_dir` + extension filter
//! is all it takes.
//!
//! The same glob also emits **one `#[test]` per preset** for the roster sweeps
//! (ADR-0157). nextest parallelizes across tests and never inside one, so a
//! sweep written as a loop over the whole library is a single serial process
//! however many cores are idle. The generated tests make the loop's assertions
//! one process at a time instead.

use std::path::{Path, PathBuf};

fn main() {
    // Resolve `presets/` from the crate manifest dir (core/..), never the CWD,
    // so generation is correct under `cargo build` from anywhere, CI, and
    // rust-analyzer. Absolute `include_str!` paths (built from the same root)
    // also resolve regardless of where in OUT_DIR the generated file lands.
    let manifest_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    let presets_dir = manifest_dir
        .parent()
        .expect("the core crate has a workspace-root parent")
        .join("presets");

    // Retrigger generation whenever the directory changes (a preset added or
    // removed). A directory `rerun-if-changed` scans its contents, and each file
    // is registered below too, so an edit to a single preset also retriggers.
    println!("cargo:rerun-if-changed={}", presets_dir.display());

    // Collect `*.toml` filenames; anything else (e.g. `presets/README.md`) is
    // skipped by the extension filter. A missing/empty dir yields an empty slice
    // (it compiles; `default_presets()` returning empty is already tolerated).
    let mut files: Vec<String> = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&presets_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|ext| ext == "toml")
                && let Some(name) = path.file_name().and_then(|n| n.to_str())
            {
                println!("cargo:rerun-if-changed={}", path.display());
                files.push(name.to_string());
            }
        }
    }
    // Deterministic embedded order (and thus the default cycle order),
    // build-to-build — matching the on-disk `load_dir` filename sort.
    files.sort();

    // `{:?}` on the filename and the absolute path emits a properly-escaped Rust
    // string literal (backslashes and quotes handled), so the generated file is
    // valid on Windows paths too.
    // The `///` doc satisfies core's `#![warn(missing_docs)]` for this generated
    // `pub` item (a doc comment can't be attached where `include!` is invoked).
    let mut out = String::from(
        "// @generated by core/build.rs from presets/*.toml (ADR-0022). Do not edit.\n\
         /// The shipped example presets, generated from `presets/*.toml` by\n\
         /// `core/build.rs` (ADR-0022): `(filename, contents)` tuples, sorted by\n\
         /// filename, each embedded via `include_str!`.\n\
         pub static EMBEDDED: &[(&str, &str)] = &[\n",
    );
    for name in &files {
        let abs = presets_dir.join(name);
        let abs = abs.to_string_lossy();
        out.push_str(&format!("    ({name:?}, include_str!({abs:?})),\n"));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"));
    std::fs::write(out_dir.join("embedded_presets.rs"), out)
        .expect("write generated embedded_presets.rs");

    let roster = roster(&presets_dir, &files);

    // Per preset: the sweeps whose claim is about one preset on its own.
    let per_preset: Vec<(String, String)> = roster
        .iter()
        .map(|(stem, name, _)| (stem.clone(), name.clone()))
        .collect();
    emit_sweep(
        &out_dir,
        "animation_tests.rs",
        "animation",
        "animates_over_time",
        &per_preset,
    );
    emit_sweep(
        &out_dir,
        "reactivity_tests.rs",
        "reactivity",
        "reacts_to_at_least_one_band",
        &per_preset,
    );
    emit_sweep(
        &out_dir,
        "sanity_loudness_tests.rs",
        "sanity_loudness",
        "louder_frame_is_reported_against_a_quieter_one",
        &per_preset,
    );

    // Per family: the sweeps whose claim is about a family's distribution and so
    // has no per-preset form. `sanity`'s shape gate fails a family whose coverage
    // floor has been left behind by its own lowest preset, which is a statement
    // about the set and not about any member of it.
    emit_sweep(
        &out_dir,
        "sanity_shape_tests.rs",
        "sanity_shape",
        "draws_a_real_shape",
        &families(&roster),
    );
}

/// `(stem, display name, system)` for every shipped preset, in `files` order.
///
/// The **stem** is the `.toml` filename without its extension: unique by
/// construction, already ident-shaped, and the handle `-E test(...)` selects on.
/// The **display name** is the preset's own `name` key, which is what the
/// renderer's roster is keyed by and what a per-preset test hands its helper —
/// the two differ for every shipped preset (`attractor_leviathan` /
/// `Leviathan`), so neither can stand in for the other. The **system** is the
/// family label, which a per-family test hands its helper instead.
fn roster(presets_dir: &Path, files: &[String]) -> Vec<(String, String, String)> {
    files
        .iter()
        .map(|file| {
            let src = std::fs::read_to_string(presets_dir.join(file))
                .unwrap_or_else(|e| panic!("read preset {file}: {e}"));
            let stem = file
                .strip_suffix(".toml")
                .expect("the extension filter admitted only `*.toml`");
            (
                ident(stem),
                preamble_string(&src, "name", file),
                preamble_string(&src, "system", file),
            )
        })
        .collect()
}

/// The distinct family labels the shipped set actually contains, sorted.
///
/// Derived from the presets rather than from `SystemKind`, for the reason the
/// glob exists at all: a family with no shipped preset would generate a test
/// that measures an empty set and passes, and a family added to the library
/// gets its test without anyone editing a list.
fn families(roster: &[(String, String, String)]) -> Vec<(String, String)> {
    let mut labels: Vec<String> = roster.iter().map(|(_, _, sys)| sys.clone()).collect();
    labels.sort();
    labels.dedup();
    labels
        .into_iter()
        .map(|label| (ident(&label), label))
        .collect()
}

/// A preset's top-level `key = "value"` from its TOML preamble.
///
/// A line scan, not a TOML parse: adding a `[build-dependencies]` parser to read
/// two scalars would be a dependency this build script has never needed. The
/// preamble is every line before the first `[section]` header, which is where
/// TOML puts the root table's keys, and every shipped preset declares `name`
/// and `system` there as a plain double-quoted value.
///
/// The trap this guards is a prefix match: `strip_prefix("name")` also accepts
/// `name_of_thing = ...`, so the `=` is required *after* the trim. A preset that
/// breaks either assumption fails the build here with its filename, rather than
/// silently losing its generated test — an absent test passes.
fn preamble_string(src: &str, key: &str, file: &str) -> String {
    for line in src.lines() {
        let line = line.trim();
        if line.starts_with('[') {
            break;
        }
        let Some(rest) = line
            .strip_prefix(key)
            .map(str::trim_start)
            .and_then(|r| r.strip_prefix('='))
            .map(str::trim)
        else {
            continue;
        };
        let value = rest
            .strip_prefix('"')
            .and_then(|r| r.split_once('"'))
            .map(|(v, _)| v)
            .unwrap_or_else(|| {
                panic!("preset {file}: `{key}` is not a plain double-quoted string: {rest}")
            });
        assert!(
            !value.contains('\\'),
            "preset {file}: `{key}` contains a backslash escape, which this scan does not decode"
        );
        return value.to_string();
    }
    panic!("preset {file}: no top-level `{key} = \"...\"` before the first [section]");
}

/// Lowercase the stem into something that is certainly a Rust identifier.
///
/// The shipped filenames are already `[a-z0-9_]`, so this is a guard rather than
/// a transform: a preset landing as `Fire-Storm.toml` becomes `fire_storm`
/// instead of a syntax error inside a generated file nobody edits.
fn ident(stem: &str) -> String {
    stem.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect()
}

/// Write one `#[test]` per item into `OUT_DIR/<file>`, each calling `helper`
/// with that item's argument (ADR-0157).
///
/// `items` is `(ident, argument)`: for a per-preset sweep that is the filename
/// stem and the preset's display name; for a per-family one it is the family
/// label twice over. One emitter serves both because the difference between
/// them is what the sweep's claim is about, not how the fan-out is written.
///
/// The sweep's own test file `include!`s the result and supplies `helper`, so
/// the assertions stay in the sweep next to the constants they gate on and only
/// the *fan-out* is generated. Naming is `<prefix>_<ident>`, which is what makes
/// a failure name its subject and `-E test(...)` select one.
fn emit_sweep(out_dir: &Path, file: &str, prefix: &str, helper: &str, items: &[(String, String)]) {
    let mut out = format!(
        "// @generated by core/build.rs from presets/*.toml (ADR-0157). Do not edit.\n\
         // `{helper}` lives in the sweep that includes this.\n"
    );
    for (id, arg) in items {
        out.push_str(&format!(
            "#[test]\nfn {prefix}_{id}() {{\n    {helper}({arg:?});\n}}\n"
        ));
    }
    std::fs::write(out_dir.join(file), out)
        .unwrap_or_else(|e| panic!("write generated {file}: {e}"));
}
