//! Animation liveness (Plan 0013 Phase 3, HARD). A scene must change over time
//! independent of audio: hold the audio frame constant and compare frame N with
//! frame N+k. A frozen scene (e.g. `time` unbound, or a stuck clock) reads as
//! near-zero and fails. Silent audio is used deliberately — the motion under
//! test is the shared scene clock, not an audio edge.
//!
//! **Plan 0077 Phase 1 / ADR-0091: motion is scored against the figure's own
//! footprint, not the whole frame.** The original statistic was
//! `metrics::frame_diff`, a mean over every pixel, which dilutes a sparse
//! figure's motion into the empty frame around it — it scores *occupancy*, and
//! Plan 0067 Phase 1d measured occupancy to be scale-invariant (the ladder at
//! the bottom of this file), so no render size fixes it. The gate now uses
//! `metrics::footprint_diff`: the same mean, taken over the union of lit
//! pixels in the two frames only. The capture roster has its `bg_*` bindings
//! stripped ([`without_backdrop`]) for the same reason sanity.rs strips them
//! (ADR-0067): a shipped backdrop's dim gradient sits above the lit threshold
//! in sRGB, and measured *with* backdrops the sparse probe's footprint read as
//! 65 % of the frame — the dilution this change exists to remove, back again
//! by another door.
//!
//! **Plan 0123 Phase 1 / ADR-0136: the gate asks its question in both
//! readings.** Autonomous motion and liveliness were the same property for
//! every world the library held when this file was written, and they stopped
//! being the same one for a poster built to sit still and do its moving in
//! response to the music. So a preset passes on **either** reading: the silent
//! motion above, or a silent-versus-driven differential — the same
//! `footprint_diff`, over the silent capture and one taken against
//! [`AnalysisFrame::fully_driven`] at the same frame count. A preset frozen in
//! **both** still fails, which is the only sense in which this gate has ever
//! meant frozen. Each preset's test prints which branch carried its pass, so
//! "still in silence" is a visible label on every preset rather than an
//! invisible consequence of an `||`.
//!
//! **The sweep is one test per preset** (ADR-0157), generated by `core/build.rs`
//! from the same `presets/*.toml` glob that emits the embedded set and
//! `include!`d below [`animates_over_time`]. nextest parallelizes across tests
//! and never inside one, so the roster written as a single `#[test]` ran on one
//! core with the rest of the box idle.
//!
//! Both branches score **this gate's own statistic**. The driven reading is not
//! `reactivity.rs`'s: that gate measures `frame_diff` — a whole-frame mean — on
//! real PCM through the real analyzer, and it stays the only gate that does.
//! Disjoining two floors on two statistics in two units would be the ADR-0071 /
//! ADR-0074 error with an `||` in front of it.
//!
//! Software adapter so it holds on any CI GPU.
//!
//! The resolution ladder at the bottom of this file (Plan 0067 Phase 1d) is a
//! **measurement, not a gate** — it is `#[ignore]`d, records why [`SIZE`] did
//! not move, and stays pinned to the whole-frame statistic it measured.

use rlx_core::dsp::AnalysisFrame;
use rlx_core::preset::{Preset, SystemKind, default_presets};
use rlx_core::render::{
    Renderer,
    metrics::{footprint_diff, frame_diff},
};

mod common;

/// Capture size for the gate.
///
/// **Measured against the two designs it penalizes at Plan 0067 Phase 1d and
/// deliberately left alone** — see [`the_resolution_ladder_against_the_two_designs_it_penalizes`]
/// for the ladder and the numbers.
const SIZE: u32 = 96;
/// The earlier and later capture points (frames). The ~0.4 s gap at the fixed
/// 60 fps `SCENE_DT` is ample for any live scene to move visibly.
const FRAME_A: u32 = 24;
const FRAME_B: u32 = 48;
/// Minimum motion between the two frames, in `metrics::footprint_diff`'s
/// mean-abs-over-the-lit-footprint units (0..1). Catches a *frozen* scene, not
/// a subtly-animated one.
///
/// **Re-derived against the footprint statistic at Plan 0077 Phase 1
/// (ADR-0091), from the same measurement the sweep above prints on every run.**
/// The whole-frame floor this replaces was also 0.01; the number surviving is
/// a coincidence of the derivation, not a constant carried over. The derivation,
/// per ADR-0071:
///
/// - **The population is the presets that pass on THIS branch**, and naming it
///   is load-bearing. A preset carried by the driven branch is still by design
///   (ADR-0136) and reads near zero here on purpose, so folding it in would
///   derive this floor from the frames the branch exists to let through.
///   Re-measured 2026-09-01, DX12 software adapter, backdrops suppressed, 81
///   shipped presets: **74 pass on this branch and their minimum is 0.0155**
///   (`Nocturne`), so the floor sits 1.55x under it. The seven the driven
///   branch carries run from `Heart Mono`'s **0.0000** up.
/// - **The floor is `0.01` because half of `0.0205` (`Banded Mandala`, measured
///   2026-08-12 on the same adapter) rounds there**, on the per-system-floor
///   ceremony `sanity.rs` uses. Half of the branch minimum above is `0.0078`,
///   so the number in force is the *stricter* of the two derivations. It stays
///   put: above what the ceremony gives on today's population, and still under
///   every preset the branch admits.
/// - **Do not re-derive by reading the top of the printed sweep.** The sweep
///   prints one line per preset with no branch filter, and its lowest rows are
///   the driven-branch worlds — the minimum off it is `0.0000` and half of
///   that admits everything, including the flicker the noise ceiling below
///   exists to exclude. Filter to the branch, then take the minimum.
/// - The noise ceiling sits **below** it: with the mask floored at
///   [`MIN_FOOTPRINT_FRAC`], the worst-case stray event ADR-0091 names (one
///   pixel swinging full-scale on all three channels in an otherwise empty
///   frame) reads `1/139 = 0.0072` — under this floor with 1.4x margin, so a
///   flicker cannot clear a gate that the branch's own minimum clears by 1.55x.
/// - The non-vacuity pair brackets it: the rejected fifth-density Squall draft
///   reads **0.1049** (10.5x the floor, against 0.0057 under the whole-frame
///   statistic that priced it out), and the static control reads **0.0000** —
///   a zero numerator, which no normalization can rescue (ADR-0091's safety
///   argument). The pair is pinned as a standing test below.
const ANIM_FLOOR: f32 = 0.01;
/// Minimum silent-versus-driven differential, in the same `footprint_diff`
/// units as [`ANIM_FLOOR`] and over the same mask — the floor the **driven**
/// branch clears (ADR-0136). A preset under both floors is frozen and fails.
///
/// **Derived from the sweep this file prints, on the convention
/// [`ANIM_FLOOR`]'s own derivation uses**, per ADR-0071:
///
/// - **The population is the presets that pass on THIS branch**, which is a
///   narrower set than the library and reads exactly like the library.
///   [`Motion::branch`] tests the silent reading first and returns, so a preset
///   that moves on its own clock is never measured against this floor at all:
///   its driven reading is a number the gate does not consult, and deriving
///   from it would fix a floor off frames it does not gate. Re-measured
///   2026-09-01, DX12 software adapter, backdrops suppressed, 81 shipped
///   presets: **seven pass on this branch and their minimum is 0.0577**
///   (`Stipple`), so the floor sits 3.4x under it. Across all 81 the median
///   driven reading is 0.19 and the maximum 0.68.
/// - **The floor is `0.017` because half of `0.0345` (`Valentine`, measured
///   2026-08-27 over 53 presets) rounds down there** — but `Valentine` passes
///   on the *silent* branch, so that derivation read the whole library rather
///   than this branch's population. The library's lowest driven reading today
///   is `Thomas on Red`'s **0.0320**, and it too is a silent-branch preset. The
///   number stands: it is well under this branch's real minimum, and moving it
///   is not what naming the population is for.
/// - The noise ceiling sits **below** it, and it is literally the same ceiling.
///   This statistic is `footprint_diff` over a mask floored at
///   [`MIN_FOOTPRINT_FRAC`], so ADR-0091's worst-case stray event — one pixel
///   swinging full-scale on all three channels in an otherwise empty frame —
///   reads `1/139 = 0.0072` here too, under this floor with 2.4x margin.
/// - The non-vacuity pair brackets it, and its low end is the sharper half.
///   `probe_collage_mono_calm` — the still-by-design world this branch exists
///   for — reads **0.0621**, 3.7x the floor. `rosette_spin_only` reads
///   **0.0000**: it turns steadily on its own clock and binds no band, so a
///   figure that moves but not *with the music* has a zero numerator here,
///   exactly as the static control does on both readings. Both are pinned as
///   standing tests below.
const DRIVEN_FLOOR: f32 = 0.017;

/// A pixel counts as lit (in the footprint) if any RGB channel differs from
/// [`BLACK`] by more than this — the sanity suite's convention, same value,
/// same reason: shrugs off near-black dithering.
const EPS: u8 = 10;
/// What the footprint is measured against. Not a sampled pixel: the backdrop is
/// suppressed for this capture ([`without_backdrop`]), so every lit pixel is
/// light the **scene** put there.
///
/// **Audited at Plan 0116 Phase 3 and deliberately left constant.** `sanity.rs`
/// now derives its reference per capture (ADR-0126) because a scene that paints
/// its own ground reads `coverage` exactly `1.0` against black. This measure
/// has no single frame to derive from — `footprint_diff` masks over the
/// **union** of two captures, so a per-frame ground would give the mask two
/// references and make the union ill-defined. It is also a *difference*: a
/// scene whose ground is a constant off-white contributes nothing to the
/// numerator whatever the reference calls it, which is the property
/// [`ANIM_FLOOR`] is derived against.
const BLACK: [u8; 4] = [0, 0, 0, 255];
/// Lower bound on `footprint_diff`'s denominator, as a fraction of the frame —
/// the guard ADR-0091 requires against a tiny mask amplifying noise. `0.015` of
/// a 96x96 frame floors the mask at **139 pixels**, which caps the one-pixel
/// full-swing flicker at `0.0072`, under [`ANIM_FLOOR`] (the derivation there).
/// The cost side: a figure lighting less than 1.5 % of the frame has its score
/// scaled down by `mask/139`. The sparsest *silent* footprint in the shipped
/// library is ~7 % of the frame (`Halo` — read any preset's mask fraction off
/// the sweep as `whole-frame / footprint`), 4.5x this bound, so no shipped
/// content is diluted. A future look that sits near this bound is being told
/// it is near-invisible at 96x96 — surface that at the coverage gate rather
/// than tuning this epsilon to pass (ADR-0091's stated risk).
const MIN_FOOTPRINT_FRAC: f32 = 0.015;

/// The prefix every background-stage parameter carries (see sanity.rs, which
/// established the convention and the guard below).
const BG_PREFIX: &str = "bg_";

/// Strip the backdrop bindings so the footprint is the **scene's** lit pixels
/// (ADR-0067's lesson, re-learned here by measurement: a shipped `bg_bright` of
/// 0.016 stores as ~34/255 in sRGB — over [`EPS`] — so with the backdrop on,
/// the "footprint" of a sparse emitter read as 65 % of the frame and the
/// statistic went straight back to diluting by emptiness). The background stage
/// defaults to a black clear, so this is removing bindings, not adding a path.
///
/// Backdrop drift (a slow `bg_hue` sweep) deliberately does **not**
/// count as animation. The gate's question is whether the *scene*
/// moves; a picture whose only life is its vignette breathing is
/// exactly what it should convict.
fn without_backdrop(mut preset: Preset) -> Preset {
    preset.params.retain(|b| !b.name.starts_with(BG_PREFIX));
    preset
}

/// The shipped library, backdrops suppressed, plus `(name, system)` per preset.
/// Panics if the transform matched nothing — the same guard-on-the-guard as
/// sanity.rs: a rename off `bg_` would silently put the backdrop back into the
/// footprint.
fn animation_roster() -> (Vec<Preset>, Vec<(String, SystemKind)>) {
    let mut stripped = 0usize;
    let presets: Vec<Preset> = default_presets()
        .into_iter()
        .map(|p| {
            let before = p.params.len();
            let p = without_backdrop(p);
            stripped += before - p.params.len();
            p
        })
        .collect();
    assert!(
        stripped > 0,
        "no `{BG_PREFIX}*` binding was found in any of the {} shipped presets — the \
         backdrop suppression the footprint statistic rests on has become a no-op",
        presets.len()
    );
    let meta = presets.iter().map(|p| (p.name.clone(), p.system)).collect();
    (presets, meta)
}

fn system_name(system: SystemKind) -> &'static str {
    match system {
        SystemKind::FragmentField => "fragment_field",
        SystemKind::Swarm => "swarm",
        SystemKind::ParametricCurve => "parametric_curve",
        SystemKind::LSystem => "lsystem",
        SystemKind::StarPattern => "star_pattern",
        SystemKind::ReactionDiffusion => "reaction_diffusion",
        SystemKind::Attractor => "attractor",
        SystemKind::Spectrum => "spectrum",
        SystemKind::Emitter => "emitter",
        SystemKind::ShapeField => "shape_field",
        SystemKind::WarpMesh => "warp_mesh",
        SystemKind::ShapeCollage => "shape_collage",
    }
}

/// One preset's three readings (ADR-0136).
#[derive(Clone, Copy)]
struct Motion {
    /// `footprint_diff` between frames [`FRAME_A`] and [`FRAME_B`] at silence:
    /// the scene's own clock, which [`ANIM_FLOOR`] gates.
    silent: f32,
    /// `footprint_diff` between the silent and the fully-driven capture, **both
    /// at [`FRAME_B`]**: the picture the music alone makes, which
    /// [`DRIVEN_FLOOR`] gates.
    driven: f32,
    /// The whole-frame mean over the silent pair — printed, never gated, and
    /// what the ladder at the bottom of this file stays pinned to.
    whole: f32,
}

impl Motion {
    /// Which branch carries this preset's pass, or `None` when it is frozen in
    /// both readings — the one verdict this gate fails on.
    ///
    /// Silent is tested first so the label names the *stronger* property when a
    /// preset has both: a world that moves on its own is reported as one even
    /// when the music moves it too. That ordering is what makes the printed
    /// `driven` roster mean "still in silence" rather than "happened to be
    /// checked second".
    fn branch(self) -> Option<&'static str> {
        if self.silent >= ANIM_FLOOR {
            Some("silent")
        } else if self.driven >= DRIVEN_FLOOR {
            Some("driven")
        } else {
            None
        }
    }
}

/// Every reading over one preset: two captures at silence, [`FRAME_A`] and
/// [`FRAME_B`] apart, plus one at [`FRAME_B`] against
/// [`AnalysisFrame::fully_driven`].
///
/// Three captures rather than four: the driven differential shares the silent
/// [`FRAME_B`] capture with the autonomous one, so the second reading costs one
/// capture per preset and both are anchored at the same point in the scene's
/// own clock.
fn motions(renderer: &mut Renderer, name: &str) -> Motion {
    let silent_audio = AnalysisFrame::default();
    let early = renderer
        .capture_preset(name, &silent_audio, FRAME_A)
        .expect("capture early frame");
    let late = renderer
        .capture_preset(name, &silent_audio, FRAME_B)
        .expect("capture late frame");
    let driven = renderer
        .capture_preset(name, &AnalysisFrame::fully_driven(), FRAME_B)
        .expect("capture driven frame");
    Motion {
        silent: footprint_diff(&early, &late, BLACK, EPS, MIN_FOOTPRINT_FRAC),
        driven: footprint_diff(&late, &driven, BLACK, EPS, MIN_FOOTPRINT_FRAC),
        whole: frame_diff(&early, &late),
    }
}

/// One preset's animation gate, as each generated `#[test]` calls it.
///
/// The whole roster is still built and handed to the renderer, because
/// [`animation_roster`]'s guard is a claim about the *library* — some preset
/// must carry a `bg_*` binding — and does not decompose to one preset. That
/// costs a TOML parse; what costs is the three captures, and those are scoped
/// to `name`.
///
/// The branch label ADR-0136 asks to be visible is printed here per preset
/// rather than collected into one list at the end of a sweep: with a test per
/// preset there is no end of a sweep to collect at, and nextest attributes the
/// line to the preset's own test either way.
fn animates_over_time(name: &str) {
    let Some(mut renderer) = common::headless(SIZE, SIZE) else {
        return;
    };

    let (presets, meta) = animation_roster();
    let system = meta
        .iter()
        .find(|(n, _)| n == name)
        .map(|(_, s)| *s)
        .unwrap_or_else(|| {
            panic!(
                "`{name}` is not in the shipped roster. The generated tests come from the same \
                 `presets/*.toml` glob as the embedded set, so this means a preset's `name` key \
                 parses to something other than what the build script scanned out of its preamble"
            )
        });
    renderer.set_presets(presets);

    let m = motions(&mut renderer, name);
    let branch = m.branch();
    println!(
        "[{}] {name:<14} frames {FRAME_A}/{FRAME_B}: silent {:.4}  driven {:.4}  -> {:<6} (whole-frame {:.4})",
        system_name(system),
        m.silent,
        m.driven,
        branch.unwrap_or("FROZEN"),
        m.whole,
    );

    assert!(
        branch.is_some(),
        "{name} animates on neither reading: silent {:.4} is under the {ANIM_FLOOR} floor and \
         driven {:.4} is under the {DRIVEN_FLOOR} floor",
        m.silent,
        m.driven,
    );
}

// One `#[test]` per shipped preset, each calling `animates_over_time` with the
// preset's `name`. Generated into OUT_DIR by `core/build.rs`, so a new `.toml`
// gets a test by existing. The test is named for the preset's FILENAME, which
// is unique and already ident-shaped, so a failure names the preset and
// `-E 'test(animation_<stem>)'` selects exactly one.
include!(concat!(env!("OUT_DIR"), "/animation_tests.rs"));

/// **The two pinned non-vacuity probes of ADR-0091, as a standing gate** (Plan
/// 0077 Phase 1): the rejected fifth-density Squall draft — the sparse-but-moving
/// design the whole-frame statistic diluted to 0.0051 — must **pass** the
/// footprint statistic, and Phase 1d's static control must keep **failing** it.
/// Together they pin the change to exactly the class ADR-0091 claims it moves:
/// if the draft ever fails, the statistic has regressed to scoring occupancy; if
/// the control ever passes, the floor has stopped gating anything.
///
/// **The control is checked on both branches** (ADR-0136). It does not move in
/// silence and it does not move under full drive — nothing in it reads `time` or
/// any band — and that pair is what frozen has always meant here. A disjunction
/// weakens a gate exactly as far as one branch and no further, so a control that
/// had to fail only one of them would stop pinning the other.
///
/// **`rosette_spin_only` is the third probe, and it is what makes the control's
/// driven zero mean anything.** A figure frozen in both readings satisfies a
/// driven statistic that measures nothing at all exactly as well as it satisfies
/// a working one. This probe turns steadily on its own clock and binds no band,
/// so it is the one frame in this file that separates *responds to the music*
/// from *moves*: its silent reading must stay above the floor (or its driven
/// zero is vacuous) and its driven reading must stay at zero.
///
/// Runs at [`SIZE`] only — the ladder below already measured that resolution
/// does not move either statistic.
#[test]
fn the_footprint_statistic_separates_the_rejected_draft_from_the_static_control() {
    let Some(mut renderer) = common::headless(SIZE, SIZE) else {
        return;
    };
    let probes = probes();
    let presets: Vec<Preset> = probes
        .iter()
        .map(|(label, _, src)| {
            let p = Preset::from_toml_str(src)
                .unwrap_or_else(|e| panic!("probe `{label}` parses: {e}"));
            without_backdrop(p)
        })
        .collect();
    let names: Vec<String> = presets.iter().map(|p| p.name.clone()).collect();
    renderer.set_presets(presets);

    let mut sparse = None;
    let mut frozen = None;
    let mut rosette = None;
    for ((label, note, _), name) in probes.iter().zip(names.iter()) {
        let m = motions(&mut renderer, name);
        println!(
            "{label:<20} silent {:.4}  driven {:.4} (whole-frame {:.4})   {note}",
            m.silent, m.driven, m.whole,
        );
        match *label {
            "squall_sparse" => sparse = Some(m),
            "star_frozen" => frozen = Some(m),
            "rosette_spin_only" => rosette = Some(m),
            _ => {}
        }
    }
    let (Some(sparse), Some(frozen), Some(rosette)) = (sparse, frozen, rosette) else {
        panic!("the probe roster no longer carries the three pinned probes");
    };
    assert!(
        sparse.silent >= ANIM_FLOOR,
        "THE REJECTED DRAFT fails the footprint statistic ({:.4} < {ANIM_FLOOR}) — \
         it has regressed to scoring occupancy (ADR-0091)",
        sparse.silent,
    );
    assert!(
        frozen.silent < ANIM_FLOOR,
        "THE STATIC CONTROL passes the SILENT branch ({:.4} >= {ANIM_FLOOR}) — \
         the floor no longer gates anything",
        frozen.silent,
    );
    assert!(
        frozen.driven < DRIVEN_FLOOR,
        "THE STATIC CONTROL passes the DRIVEN branch ({:.4} >= {DRIVEN_FLOOR}) — a \
         figure with no audio binding is moving under full drive, so the driven \
         floor is measuring something other than the music (ADR-0136)",
        frozen.driven,
    );
    // The static control's driven zero above is consistent with a driven
    // statistic that measures nothing at all: a figure frozen in both
    // readings satisfies it exactly as well. This probe is what separates
    // the two. It turns steadily on its own clock and binds no band, so it
    // moves in silence and must still read zero on the differential.
    assert!(
        rosette.silent >= ANIM_FLOOR,
        "THE SYMMETRIC CASE stopped moving in silence ({:.4} < {ANIM_FLOOR}) \
         - its driven zero below is then vacuous, and this file no longer \
         holds the driven reading to responding to the music rather than \
         to motion",
        rosette.silent,
    );
    assert!(
        rosette.driven < DRIVEN_FLOOR,
        "THE SYMMETRIC CASE passes the DRIVEN branch ({:.4} >= {DRIVEN_FLOOR}) \
         - it binds no band, so autonomous motion has leaked into the \
         driven differential and the branch is scoring rotation as \
         reactivity (ADR-0136)",
        rosette.driven,
    );
}

/// **The world the driven branch exists for, measured before anything depends on
/// it** (Plan 0123 Phase 1): `collage_mono` at the `pan_x`/`pan_y` rates its
/// composition asked for must fail the silent branch and pass the driven one.
///
/// The shipped file is read through [`include_str!`] and its two rate lines are
/// rewritten here, so this measures the preset the content lane wants **without
/// editing it**: the gate is shown to carry the case before the preset depends
/// on it doing so. If the rates in the file come down to these, this probe
/// measures the shipped preset and still asserts the same property.
///
/// The assertion on the *silent* branch is the load-bearing half. Without it a
/// preset that started animating on its own would pass this test while the
/// driven branch went unexercised, and the case ADR-0136 added it for would have
/// quietly stopped being covered.
#[test]
fn the_driven_branch_carries_the_world_that_is_still_by_design() {
    let Some(mut renderer) = common::headless(SIZE, SIZE) else {
        return;
    };
    let src = with_param(
        &with_param(
            &with_param(COLLAGE_MONO_SRC, "pan_x", "0.06 * sin(time * 0.07)"),
            "pan_y",
            "0.04 * sin(time * 0.09 + 1.1)",
        ),
        "name",
        "probe_collage_mono_calm",
    );
    let preset = without_backdrop(
        Preset::from_toml_str(&src).unwrap_or_else(|e| panic!("the calm probe parses: {e}")),
    );
    let name = preset.name.clone();
    renderer.set_presets(vec![preset]);

    let m = motions(&mut renderer, &name);
    println!(
        "{name:<24} silent {:.4}  driven {:.4}  -> {:<6} (whole-frame {:.4})",
        m.silent,
        m.driven,
        m.branch().unwrap_or("FROZEN"),
        m.whole,
    );
    assert!(
        m.silent < ANIM_FLOOR,
        "THE CALM PROBE clears the silent floor ({:.4} >= {ANIM_FLOOR}) — it is not \
         the still-by-design case the driven branch was added for, so this test \
         has stopped exercising that branch",
        m.silent,
    );
    assert!(
        m.driven >= DRIVEN_FLOOR,
        "THE CALM PROBE fails the driven floor ({:.4} < {DRIVEN_FLOOR}) — the \
         branch ADR-0136 added does not carry the preset it was added for",
        m.driven,
    );
}

// ---------------------------------------------------------------------------
// The resolution ladder (Plan 0067 Phase 1d) — a measurement, not a gate
// ---------------------------------------------------------------------------

/// Rungs of the ladder. 384 is 16x the pixels of 96, which is why this is not
/// something the shipped-set sweep above can afford to run at.
const LADDER: [u32; 3] = [96, 192, 384];

/// **`collage_mono` as it ships**, read from the file rather than frozen into
/// this one — the opposite choice from [`SQUALL_SRC`] and [`ROSETTE_SRC`] and for
/// the opposite reason. Those two are *instruments* whose rungs must stay
/// comparable across runs, so their subject is pinned. This one is a claim
/// **about the shipped preset**, so it has to follow the file: a frozen copy
/// would go on asserting that the driven branch carries a preset the library
/// does not contain.
const COLLAGE_MONO_SRC: &str = include_str!("../../presets/collage_mono.toml");

/// **`Squall` exactly as it shipped**, frozen here when Plan 0075's cohort four
/// retired the file (recover the commented original with
/// `git log --diff-filter=D -- presets/emitter_squall.toml`) — the treatment
/// `ROSETTE_SRC` below prescribed for it.
const SQUALL_SRC: &str = r##"
system = "emitter"
name = "Squall"

[palette]
stops = [
  { at = 0.00, color = "#263856" },
  { at = 0.28, color = "#5f88b8" },
  { at = 0.58, color = "#97c5ec" },
  { at = 0.84, color = "#d5ebfb" },
  { at = 1.00, color = "#f9fcff" },
]

[params]
spawn_rate = "470 + clamp(bass * 329, 0, 280) + clamp(onset * 424, 0, 254)"
launch_speed = "5.60 + clamp(mid * 0.494, 0, 0.42)"
gravity      = "6.4"
launch_angle = "0.92 + sin(time * 0.061) * 0.13"
spread          = "0.30 + clamp(onset * 0.20, 0, 0.12)"
size_spread     = "0.70"
lifetime_spread = "0.55"
lifetime = "1.7"
size     = "2.05 + clamp(treb * 0.633, 0, 0.38)"
spin    = "0.85 + clamp(mid * 0.741, 0, 0.63)"
twinkle = "0.52 + clamp(treb * 0.467, 0, 0.28)"
brightness = "1.12 + clamp(bass * 0.400, 0, 0.34)"
hue        = "mod(0.60 + time * 0.009, 1)"
hue_spread = "0.38 + clamp(treb * 0.300, 0, 0.18)"
hue_center = "0.58"
saturation = "0.98"
zoom  = "1.00"
pan_x = "sin(time * 0.031) * 0.05"
trails      = "0.44 + clamp(mid * 0.188, 0, 0.16)"
bg_hue      = "0.30 + sin(time * 0.014) * 0.03"
bg_bright   = "0.016 + clamp(treb * 0.0217, 0, 0.013)"
bg_vignette = "0.68"

[smoothing]
spawn_rate   = { attack = 0.05, release = 0.58 }
launch_speed = { attack = 0.10, release = 0.40 }
launch_angle = 0.85
brightness   = { attack = 0.06, release = 0.32 }
size         = { attack = 0.07, release = 0.38 }
hue_spread   = 0.9
trails       = 0.50
bg_bright    = 0.30
"##;

/// **`Star Rosette` exactly as it shipped**, frozen here when Plan 0075's
/// cohort one retired the file (recover the commented original with
/// `git log --diff-filter=D -- presets/star_rosette.toml`). The ladder is a
/// *measurement* whose rungs must stay comparable across runs, so its probe
/// subject is frozen content, not the live library — the same reasoning that
/// froze the sanity suite's mandalas and ADR-0023's golden fixtures.
/// `SQUALL_SRC` above took this same treatment at cohort four.
const ROSETTE_SRC: &str = r#"
system = "star_pattern"
name = "Star Rosette"
[generator]
tiling            = "12"
contact_angle_deg = 20
[params]
variant = "2 * abs(mod(0.5 + time * 0.021 + clamp(bass * 0.41, 0, 0.35), 2) - 1)"
rotation = "0.80 * time + sin(time * 0.031) * 0.26"
draw_progress = "clamp(0.52 + sin(time * 0.20) * 0.42 + bar * 0.20 + clamp(onset * 0.333, 0, 0.20), 0, 1)"
thickness  = "1.70 + clamp(bass * 3.06, 0, 2.6) + beat * 0.40"
brightness = "0.66 + clamp(mid * 0.53, 0, 0.45)"
scale      = "0.58 + sin(time * 0.14) * 0.13 + bar * 0.05 + clamp(bass * 0.47, 0, 0.40)"
hue        = "0.50 + time * 0.023 + clamp(treb * 0.75, 0, 0.45)"
mirror_order   = "select(mid > 0.58, 7, 5)"
mirror_reflect = "0"
zoom        = "1.06 + bar * 0.06 + clamp(bass * 0.176, 0, 0.15)"
pan_x       = "sin(time * 0.0170) * 0.05"
bg_hue      = "0.10 + sin(time * 0.0091) * 0.06"
bg_bright   = "0.018 + clamp(mid * 0.0153, 0, 0.013)"
bg_vignette = "0.82"
trails = "0.34 + clamp(mid * 0.082, 0, 0.07)"
[smoothing]
mirror_order  = 2.5
variant       = 1.5
rotation      = 0.18
thickness     = { attack = 0.02, release = 0.34 }
scale         = 0.55
hue           = 0.42
zoom          = 0.18
bg_bright     = 0.40
trails       = 0.55
"#;

/// A 12-fold Hankin rosette whose **only** motion is rotation — design-backlog
/// 0009's symmetric case, isolated. `star_rosette` as shipped works around the
/// problem by sweeping `draw_progress` radially and breathing `scale`; this
/// probe removes the workaround so what is measured is the rotation alone.
const STAR_SPIN: &str = r#"
system = "star_pattern"
name   = "probe_star_spin"

[generator]
tiling            = "12"
contact_angle_deg = 20

[params]
variant       = "1"
rotation      = "0.80 * time"
hue           = "0.5"
draw_progress = "1"
thickness     = "1.7"
scale         = "0.58"
brightness    = "0.9"
"#;

/// The static control: [`STAR_SPIN`] with the rotation taken out, so nothing in
/// it reads `time` or any band. It must keep failing the floor at every rung —
/// a resolution that lets *this* through would have made the gate worthless.
const STAR_FROZEN: &str = r#"
system = "star_pattern"
name   = "probe_star_frozen"

[generator]
tiling            = "12"
contact_angle_deg = 20

[params]
variant       = "1"
rotation      = "0"
hue           = "0.5"
draw_progress = "1"
thickness     = "1.7"
scale         = "0.58"
brightness    = "0.9"
"#;

/// The `key = "<expr>"` line of a preset source, split into (line, expr).
/// Panics when the key is absent, so a rename upstream fails this probe loudly
/// instead of silently measuring the shipped preset twice.
fn param_line<'a>(src: &'a str, key: &str) -> (&'a str, &'a str) {
    let line = src
        .lines()
        .find(|l| {
            l.trim_start()
                .strip_prefix(key)
                .is_some_and(|rest| matches!(rest.trim_start().chars().next(), Some('=')))
        })
        .unwrap_or_else(|| panic!("`{key}` is not a param of this preset source"));
    let expr = line
        .split_once('=')
        .map(|(_, rest)| rest.trim().trim_matches('"'))
        .unwrap_or_else(|| panic!("`{key}` has no value"));
    (line, expr)
}

/// Rewrite one `key = "..."` line's value, keeping the rest of the file byte for
/// byte. The probes are built out of the shipped sources this way so they cannot
/// drift into being a different preset than the one 0009 is about.
fn with_param(src: &str, key: &str, value: &str) -> String {
    let (line, _) = param_line(src, key);
    src.replace(line, &format!("{key} = \"{value}\""))
}

/// The five probes, as `(label, note, source)`.
fn probes() -> Vec<(&'static str, &'static str, String)> {
    let (_, spawn) = param_line(SQUALL_SRC, "spawn_rate");
    let sparse = with_param(
        &with_param(SQUALL_SRC, "spawn_rate", &format!("({spawn}) * 0.2")),
        "name",
        "probe_squall_sparse",
    );
    let squall = with_param(SQUALL_SRC, "name", "probe_squall_shipped");
    let rosette = with_param(ROSETTE_SRC, "name", "probe_rosette_shipped");
    vec![
        (
            "squall_shipped",
            "the density that clears the floor",
            squall,
        ),
        (
            "squall_sparse",
            "THE REJECTED DRAFT — spawn_rate at a fifth",
            sparse,
        ),
        (
            "rosette_shipped",
            "the symmetric design, with its radial workaround",
            rosette,
        ),
        (
            "rosette_spin_only",
            "THE SYMMETRIC CASE — rotation is the only motion",
            STAR_SPIN.to_string(),
        ),
        (
            "star_frozen",
            "STATIC CONTROL — must fail at every rung",
            STAR_FROZEN.to_string(),
        ),
    ]
}

/// **The Plan 0067 Phase 1d measurement, and its answer: resolution does not
/// separate a sparse-but-moving frame from a static one.** `#[ignore]`d because
/// it is an instrument rather than a gate — the 384 rung alone is 16x the pixels
/// of the sweep above. Run it with:
///
/// ```bash
/// cargo nextest run -p rlx-core --test animation --run-ignored all --no-capture
/// ```
///
/// Measured 2026-08-09, DX12 software adapter (`frame_diff`, frames 24 vs 48,
/// silent audio; `ANIM_FLOOR` is 0.01). Whole run: **7.6 s**.
///
/// ```text
/// probe                    96      192      384   change over 16x the pixels
/// squall_shipped       0.0187   0.0187   0.0188   +0.0001
/// squall_sparse        0.0051   0.0051   0.0049   -0.0002   THE REJECTED DRAFT
/// rosette_shipped      0.0218   0.0212   0.0208   -0.0010
/// rosette_spin_only    0.0103   0.0100   0.0103    0.0000   THE SYMMETRIC CASE
/// star_frozen          0.0000   0.0000   0.0000    0.0000   STATIC CONTROL
/// ```
///
/// **Every row is flat.** Across a 16x change in pixel count no probe moves by
/// more than 0.001, and none crosses the floor. The two rows the phase exists
/// for — the rejected sparse draft at 0.005 and the isolated symmetric case at
/// 0.010 — sit exactly where they sat at 96. Resolution is not the lever.
///
/// **Half of that was settled before a pixel was rendered.** A figure invariant
/// under rotation by `2*pi/k` renders an identical image under that rotation, so
/// its whole-frame difference is zero at *every* resolution and no ladder could
/// rescue it. `rosette_spin_only` is the empirical half: a 12-fold rosette turns
/// ~18 degrees between the two capture points, which is not a symmetry of the
/// figure, so it does not read zero — it reads 0.0103, clearing the floor by
/// 3 % where the shipped `star_rosette` clears it by 118 %. The penalty
/// design-backlog 0009 describes is real and it is roughly a halving; what it is
/// not is a sampling artifact.
///
/// **The sparse case was the one plausibly resolution-bound, and it is not.**
/// The hypothesis was that a mark smaller than a pixel at 96x96 is lost rather
/// than area-averaged, so rendering larger would recover its motion. Squall's
/// rejected draft reads 0.0051 at 96 and 0.0049 at 384 — very slightly *worse*,
/// which is the mechanism showing through: `frame_diff` is a **mean over the
/// frame**, so the marks and the dark they are averaged against grow together.
/// Both of 0009's designs fail for the same reason and it is not resolution — a
/// mean-over-the-frame statistic scores **occupancy**, and occupancy is
/// scale-invariant.
///
/// **So neither [`SIZE`] nor [`ANIM_FLOOR`] moves, and the CI cost of that choice
/// is zero.** 192 would have cost the whole-library sweep 4x the pixels and 384
/// 16x, for a reading that changes in the third decimal place.
///
/// **One thing the table shows that is deliberately not acted on.** The sparse
/// draft (0.0051) and the static control (0.0000) *are* separated, so a floor
/// near 0.004 would pass the draft and still convict the control. That is not a
/// finding this phase may spend: the control here is a *perfectly* frozen figure
/// and a real near-frozen preset lands somewhere between the two, so the gap is
/// an upper bound on the headroom rather than the headroom. 0009 says the same
/// thing in its own words — "a floor that a genuinely static preset can clear is
/// worth nothing" — and lowering it on one synthetic control would be exactly
/// the blind give-away it warns against.
///
/// Per the phase, this is a **successful negative result**: it forecloses the
/// cheap fix and leaves standing 0009's real successor — a coverage-aware
/// statistic that normalizes motion by the **lit area** rather than by the frame.
/// This table is the evidence that it is the only remaining option.
///
/// **That successor landed at Plan 0077 Phase 1 (ADR-0091)** — the gate above
/// now scores `metrics::footprint_diff`. This ladder deliberately keeps
/// measuring the whole-frame statistic it is pinned to: its table is the
/// recorded evidence for why the statistic had to change, and re-pointing the
/// instrument at the new statistic would erase the comparison the numbers
/// exist to hold. Under the footprint statistic the rejected draft reads
/// 0.1049 against the shipped 0.1093 — the density difference cancels, which
/// is the whole claim — and the static control keeps its zero numerator.
///
/// **Being `#[ignore]`d has a cost worth naming:** the two probes rebuilt from
/// shipped sources go through [`param_line`], which panics if `spawn_rate` or
/// `name` is renamed — and a panic in an ignored test is silent. If this is run
/// after a preset edit and it panics, the probe needs updating, not the preset.
#[test]
#[ignore = "measurement, not a gate: the 384 rung is 16x the pixels of the sweep"]
fn the_resolution_ladder_against_the_two_designs_it_penalizes() {
    let probes = probes();
    let mut rows: Vec<(&str, &str, Vec<f32>)> = probes
        .iter()
        .map(|(label, note, _)| (*label, *note, Vec::new()))
        .collect();

    for size in LADDER {
        let Some(mut renderer) = common::headless(size, size) else {
            return;
        };
        let presets: Vec<Preset> = probes
            .iter()
            .map(|(label, _, src)| {
                Preset::from_toml_str(src).unwrap_or_else(|e| panic!("probe `{label}` parses: {e}"))
            })
            .collect();
        let names: Vec<String> = presets.iter().map(|p| p.name.clone()).collect();
        renderer.set_presets(presets);
        for (row, name) in rows.iter_mut().zip(names.iter()) {
            row.2.push(motions(&mut renderer, name).whole);
        }
    }

    print!("\n{:<20}", "probe");
    for size in LADDER {
        print!("{size:>9}");
    }
    println!("   note");
    for (label, note, values) in &rows {
        print!("{label:<20}");
        for v in values {
            print!("{v:>9.4}");
        }
        println!("   {note}");
    }
    println!("\n(ANIM_FLOOR = {ANIM_FLOOR})");

    // The one thing this measurement must not be allowed to be quietly wrong
    // about: if the static control ever animates, every row above is noise.
    let frozen = rows
        .iter()
        .find(|(label, _, _)| *label == "star_frozen")
        .map(|(_, _, v)| v.clone())
        .unwrap_or_default();
    assert!(
        frozen.iter().all(|&v| v < ANIM_FLOOR),
        "the static control animates at some rung — the ladder is measuring \
         something other than motion: {frozen:?}"
    );
}
